global:
  scrape_interval: 30s
  evaluation_interval: 25s

scrape_configs:
  - job_name: example-api-metrics
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8081']
